import CompanyLogo from './CompanyLogo';
import ReportHeader from './ReportHeader';

export default function PrintableReportDocument({ report }) {
  const columns = report?.columns || [];
  const rows = report?.rows || [];
  const summaryCards = report?.summaryCards || [];
  const company = report?.company || {};

  return (
    <article className="print-container print-report report-preview-card a4-paper flagship-a4-paper">
      <div className="print-margin-guide no-print" aria-hidden="true" />
      <ReportHeader {...company} title={report?.title || 'Cash Management Dashboard Report'} preparedBy={report?.preparedBy} />
      <section className="report-section report-company-banner">
        <CompanyLogo logo={company.companyLogo} name={company.companyName} size="lg" />
        <div>
          <h1>{company.companyName || 'BAWAR STAR PLASTIC INDUSTRY'}</h1>
          <p>{report?.subtitle || 'Premium Manufacturing & Plastic Packaging Solutions'}</p>
        </div>
      </section>

      {report?.error && (
        <section className="report-section report-error-box">
          <h3>Report unavailable</h3>
          <p>{report.error}</p>
        </section>
      )}

      {!!summaryCards.length && (
        <section className="report-section">
          <h3>Summary</h3>
          <div className="report-metric-grid">
            {summaryCards.map((card) => (
              <div key={card.label} className={card.tone ? `metric-${card.tone}` : undefined}>
                <span>{card.label}</span>
                <strong>{card.value}</strong>
                {card.detail && <em>{card.detail}</em>}
              </div>
            ))}
          </div>
        </section>
      )}

      <section className="report-section">
        <h3>{report?.tableTitle || 'Recent Transactions'}</h3>
        <table className="report-table">
          <colgroup>
            {columns.map((column) => (
              <col key={column.key} style={column.width ? { width: column.width } : undefined} />
            ))}
          </colgroup>
          <thead>
            <tr>
              {columns.map((column) => (
                <th key={column.key} className={column.align === 'right' ? 'currency-cell' : undefined}>{column.label}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.length ? rows.map((row, index) => (
              <tr key={row.id || `${report?.type || 'report'}-${index}`} dir="auto">
                {columns.map((column) => (
                  <td key={column.key} className={column.align === 'right' ? 'currency-cell' : undefined}>
                    {row[column.key] ?? '-'}
                  </td>
                ))}
              </tr>
            )) : (
              <tr>
                <td colSpan={Math.max(columns.length, 1)}>No records available for this report.</td>
              </tr>
            )}
          </tbody>
        </table>
      </section>

      <footer className="report-footer">
        <span>{report?.footerText || 'Generated by System'}</span>
        <span>{report?.generatedAt || new Date().toLocaleString()}</span>
      </footer>
    </article>
  );
}
